### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by mrx23dot** [tiborbaksa/vlc-mediaklikk-video#4]
1. I copied in plugin to given VLC folder.
2. I extracted, video source:
https://player.mediaklikk.hu/playernew/player.php?video=U2FsdGVkX19rRYKv4e2BB1vBEuxQPS1MfqngbkIfBjOeKsJRa1%2BPcGK1iC29Uh%2FjEdsJvUEFh5bBRvvNE94lGJw9U9wfkRCzPC0Ldpq0xT20w8zC8ED2OKbPGU06p4ThYUstJOufzcxhk7Q%2BvzWKLLb5Jf4vMlwHfIiV5NdWC%2Bc%3D
3. opened with CTRL-O in VLC

4. but it says:

Connection failed:
VLC could not connect to ":554".
Your input can't be opened:
VLC is unable to open the MRL ''. Check the log for details.
Connection failed:

Köszönöm!

**Comment by tiborbaksa** [comment]
Hi @mrx23dot, I'm sorry for the late reply, I haven't noticed this issue.

You should use the URL of the page where the video is embedded, not the URL of the embedded player. The parser will find the videos embedded in the page and add them to the playlist. Please let me know if this works for you, or in your use case you can only provide the embedded player URL.

While it wouldn't be hard to handle these URLs in the parser function, it is currently a bit complicated due to [VLC issue #18801](https://trac.videolan.org/vlc/ticket/18801), which is worked around by explicitly excluding the player URLs from parsing:
https://github.com/tiborbaksa/vlc-mediaklikk-video/blob/8b6793c6a7d09f12f70dd0863b1cbcbe2be0f7bc/mediaklikk-video.lua#L18
Because of this the only way I can think of to add this functionality is to split the current script into two scripts, one that extracts the player URLs from the page and one that extracts the actual stream URL from the embedded player. This would allow you to use the player URL directly, however it would make installation more complicated, I don't know if [VLC-Addons](https://addons.videolan.org) accepts multiple lua scripts in one package.

**Comment by tiborbaksa** [comment]
The fix to #5 also fixes this issue.
